---
title: "Write clear, efficient, and well-documented R programs."
description: |
author:
  - name: Courtney Rose
preview: write.png
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### 1. I can use a project-based workflow to organize and run reproducible analyses.

I have learned to use Github to store all my RStudio projects/activities/homeworks throughout the semester, so that is how I keep my project-based workflow. 
I have also learned to use the set.seed() function to get the same results everytime thus proving that I can run reproducible analyses. 


### 2. I can write professional reports using R Markdown.
I feel confident working in R Markdown, I also enjoy learning new things along the way and struggling through them. I hope that my reports look professional, but I do think that I have a long way to go and a lot to learn on this aspect. I have definitely improved throughout the semester, so I am going to say that I have achieved this subobjective. 


### 3. I can call a separate R script containing self-created functions to then be used within an analysis.
I honestly don't think I can do this one.


### 4. I can write comments that explain the “why” (Why did you choose this approach instead of an alternative? What else did you try that didn’t work?) of my code.

I think my comments throughout my coding are informative of what I am doing in my code. I always try to write descriptive comments, so that I can go back and not be confused
about what I am doing. I am sure that I could improve my brevity, but I am still working on that.


